source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_modular_headers!
target 'WebRTC-Demo' do
    pod 'netfox'
    pod 'Alamofire'
    pod "PromiseKit", "~> 6.8"
    pod 'CocoaMQTT' 
    pod 'GoogleWebRTC'
    pod 'CocoaAsyncSocket'
end
